name: testsuite
on: [push, pull_request]
jobs:
  testsuite-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: make tests
  testsuite-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang
      - run: make tests

